name: Tag PR Commits

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  tag_pr_commits:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch all tags
        run: git fetch --tags

      - name: Run versioning script
        run: .github/versioning.sh
        
      - name: Push tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push origin --tags
